#!/usr/bin/env python3
"""Build a balanced trace_id queue for batch_review.py.

The model's accept-bias on borderline cases isn't a refine-data-density problem
(the simulated pool is already 70% refine) — it's a high-weight ground-truth
shortage: only 8 operator-reviewed cases drive the weight=6-8 signal, and 4
of those have no rendered PNG so the multimodal head can't see them.

This script emits a prioritized queue of ~30 candidates that:
  1. Cover targets with zero existing reviewed cases first
  2. Include traces where the model recommended `accept` with high
     confidence (catches the bias directly — many of those should be refine)
  3. Only include traces that have a PNG asset on disk (multimodal-trainable)
  4. Spread across all scenario packs

Output:
    review_queue.txt — one trace_id per line, in priority order
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ASSETS_DIR = REPO_ROOT / "review_queue_assets"
TRACES_PATH = REPO_ROOT / "src" / "sim" / "data" / "observation_vla" / "traces.json"
OUTCOMES_PATH = REPO_ROOT / "src" / "sim" / "data" / "observation_vla" / "outcomes.json"


def _has_asset(trace_id: str) -> bool:
    return any(ASSETS_DIR.glob(f"*{trace_id}*.png"))


def _trace_target_key(trace: dict) -> str:
    return trace.get("target_id") or (trace.get("sample") or {}).get("target_id") or "unknown"


def _trace_recommended(trace: dict) -> tuple[str, float]:
    a = trace.get("assessment") or {}
    ev = a.get("evidence") or {}
    return (a.get("recommended_action") or "?", float(ev.get("confidence") or 0.0))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "review_queue.txt")
    parser.add_argument("--size", type=int, default=30, help="Target queue size.")
    parser.add_argument("--per-target-cap", type=int, default=4,
                        help="Max candidates per target (prevents one target dominating).")
    args = parser.parse_args()

    traces = json.loads(TRACES_PATH.read_text())
    traces = traces.get("traces", traces) if isinstance(traces, dict) else traces

    outcomes = json.loads(OUTCOMES_PATH.read_text()).get("outcomes", [])
    reviewed_trace_ids = {o["trace_id"] for o in outcomes if o.get("label_source") == "operator_review"}
    reviewed_per_target = defaultdict(int)
    for o in outcomes:
        if o.get("label_source") != "operator_review":
            continue
        for t in traces:
            if t.get("trace_id") == o["trace_id"]:
                reviewed_per_target[_trace_target_key(t)] += 1
                break

    # Filter: unlabeled, has asset
    unlabeled = [
        t for t in traces
        if t.get("trace_id") not in reviewed_trace_ids and _has_asset(t["trace_id"])
    ]

    # Score: lower = higher priority
    #   +0   target has 0 reviewed cases
    #   +5   target has 1 reviewed
    #   +10  target has 2+ reviewed
    #   +0   model recommended=accept with confidence>=0.7 (bias-busting candidate)
    #   +3   model recommended=refine with confidence>=0.7
    #   +5   anything else
    def score(trace):
        target = _trace_target_key(trace)
        rev = reviewed_per_target.get(target, 0)
        coverage = 0 if rev == 0 else (5 if rev == 1 else 10)
        action, conf = _trace_recommended(trace)
        if action == "accept" and conf >= 0.7:
            bias = 0
        elif action == "refine" and conf >= 0.7:
            bias = 3
        else:
            bias = 5
        return coverage + bias

    unlabeled.sort(key=score)

    # Apply per-target cap
    chosen: list[str] = []
    per_target = defaultdict(int)
    for t in unlabeled:
        if len(chosen) >= args.size:
            break
        target = _trace_target_key(t)
        if per_target[target] >= args.per_target_cap:
            continue
        chosen.append(t["trace_id"])
        per_target[target] += 1

    # Header summarizing what's in the queue
    lines = [
        "# Generated by build_review_queue.py",
        f"# {len(chosen)} candidates  per_target_cap={args.per_target_cap}",
        "# Target spread:",
    ]
    for target, n in sorted(per_target.items()):
        existing = reviewed_per_target.get(target, 0)
        lines.append(f"#   {target}: +{n}  (existing reviewed: {existing})")
    lines.append("")
    lines.extend(chosen)

    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(chosen)} candidates → {args.out}")
    print(f"Target coverage delta:")
    for target, n in sorted(per_target.items()):
        existing = reviewed_per_target.get(target, 0)
        print(f"  {target:32s}  reviewed: {existing} -> {existing + n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
